name: createImageService CI/CD

on:
  push:
    branches:
      - createImageService
  pull_request:
    branches:
      - createImageService

jobs:
  gateway-CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 내 파일들 checkout(불러오기) 수행
        uses: actions/checkout@v4

      - name: .env 파일 동적 생성
        run: |
          echo "${{ secrets.CHANGE_SERVICE_ENV_IMAGE }}" > ./.env
          ls -a

      - name: 대기 시간 추가
        run: |
          sleep 5

      - name: 파일 압축
        run: |
          echo "압축 시작 전 파일 확인"
          ls -a
          echo "압축 시작"
          tar --exclude='./.git' --ignore-failed-read -czvf run.tar.gz ./ 
          echo "압축 완료..."
          ls -a

      - name: EC2에 파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_IMAGE }}
          username: ${{ secrets.EC2_USER_IMAGE }}
          key: ${{ secrets.EC2_KEY_IMAGE }}
          source: run.tar.gz
          target: /home/ubuntu/createImageService/demo

      - name: SSH로 ec2에 접속 후, 서버 가동
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_IMAGE }}
          username: ${{ secrets.EC2_USER_IMAGE }}
          key: ${{ secrets.EC2_KEY_IMAGE }}
          script_stop: true
          script: |
            echo "📂 EC2 서버 내 파일 확인"
            ls -l /home/ubuntu/createImageService/demo

            echo "📦 압축 파일 이동 및 해제"
            mv /home/ubuntu/createImageService/demo/run.tar.gz /home/ubuntu/createImageService/run.tar.gz
            cd /home/ubuntu/createImageService
            tar -xzvf run.tar.gz

            echo "📂 압축 해제 후 파일 확인"
            ls -a  # 압축 후 파일 목록을 출력하여 requirements.txt가 존재하는지 확인

            echo "🚀 기존 프로세스 종료 (8080 포트)"
            fuser -k -n tcp 8080 || true

            echo "🐍 Python 및 가상 환경 준비"
            sudo apt update && sudo apt install -y python3 python3-venv python3-pip
            sudo apt install -y pkg-config cmake libdbus-1-dev libglib2.0-dev  # glib-2.0 패키지 추가
            rm -rf venv
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip

            # requirements.txt에서 cloud-init과 command-not-found 제거
            sed -i '/cloud-init==24.4/d' requirements.txt  # cloud-init 제거
            sed -i '/command-not-found==0.3/d' requirements.txt  # command-not-found 제거
            sed -i '/distro-info==1.7+build1/d' requirements.txt  # distro-info 제거
            pip install -r requirements.txt  # requirements.txt 설치

            echo "✅ 서버 실행"
            nohup python3 main.py > ./output.log 2>&1 &

            echo "🧹 불필요한 파일 정리"
            rm -rf /home/ubuntu/createImageService/demo
