name: Deploy Flask App and Gateway CI/CD

on:
  push:
    branches:
      - createImageService  # 배포할 브랜치 지정
  pull_request:
    branches:
      - createImageService

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ .env 파일 생성
      - name: Create .env file
        run: |
          echo "${{ secrets.CHANGE_SERVICE_ENV_IMAGE }}" > ./.env
          ls -a

      # 3️⃣ Python3 및 의존성 설치
      - name: Install Python3 and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install flask requests pandas

      # 4️⃣ Flask 앱 파일을 EC2에 업로드
      - name: Upload Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_IMAGE }}
          username: ${{ secrets.EC2_USER_IMAGE }}
          key: ${{ secrets.EC2_KEY_IMAGE }}
          source: "."
          target: "/home/ubuntu/flask-app"

      # 5️⃣ Flask 앱 실행
      - name: Run Flask App on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_IMAGE }}
          username: ${{ secrets.EC2_USER_IMAGE }}
          key: ${{ secrets.EC2_KEY_IMAGE }}
          script: |
            cd /home/ubuntu/flask-app
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo fuser -k 5000/tcp || true
            nohup python app.py > output.log 2>&1 &

      # 6️⃣ Gateway 파일 압축
      - name: Compress files for Gateway
        run: |
          tar --exclude='./.git' --ignore-failed-read -czvf run.tar.gz ./
          ls -a

      # 7️⃣ Gateway 파일을 EC2에 업로드
      - name: Upload compressed files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_IMAGE }}
          username: ${{ secrets.EC2_USER_IMAGE }}
          key: ${{ secrets.EC2_KEY_IMAGE }}
          source: run.tar.gz
          target: /home/ubuntu/createImageService

      # 8️⃣ Gateway 서비스 실행
      - name: Run Gateway Service on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CHANGE_SERVICE_EC2_HOST }}
          username: ${{ secrets.CHANGE_SERVICE_EC2_USER }}
          key: ${{ secrets.CHANGE_SERVICE_EC2_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/createImageService
            fuser -k -n tcp 5000 || true
            tar -xzvf run.tar.gz
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            nohup python3 main.py > output.log 2>&1 &
            rm -rf /home/ubuntu/createImageService/demo
